export const products = [
    {
      id: 1,
      name: "风神瞳Anemoculus Collecting ",
      description: "每日委托的四个任务",
      price: 10,
      image: "https://example.com/product1.jpg",
     
    },
    {
      id: 2,
      name: "岩神瞳Geoculus Collecting",
      description: "Description of Product 2",
      price: 12,
      image: "https://example.com/product2.jpg",
      
    },
    {
      id: 3,
      name: "忍冬果实Crimson Agates Collecting",
      description: "Description of Product 2",
      price: 15,
      image: "https://example.com/product2.jpg",
      value2: [16, 48],
      marks: {
        0: '0level',
        26: '26level',
        37: '37level',
        54: '54level',
        90: '90level',
      },
    },
    {
      id: 4,
      name: "Electroculus Collecting雷神瞳",
      description: "Description of Product 2",
      price: 200,
      image: "https://example.com/product2.jpg",
      value2: [16, 48],
      marks: {
        0: '0level',
        26: '26level',
        37: '37level',
        54: '54level',
        90: '90level',
      },
    },
    {
      id: 2,
      name: "Product 2",
      description: "Description of Product 2",
      price: 200,
      image: "https://example.com/product2.jpg",
      value2: [16, 48],
      marks: {
        0: '0level',
        26: '26level',
        37: '37level',
        54: '54level',
        90: '90level',
      },
    },
    {
      id: 2,
      name: "Product 2",
      description: "Description of Product 2",
      price: 200,
      image: "https://example.com/product2.jpg",
      value2: [16, 48],
      marks: {
        0: '0level',
        26: '26level',
        37: '37level',
        54: '54level',
        90: '90level',
      },
    },
];